
keycloak:
  realm: pmp-realm
  auth-server-url: http://localhost:8080
  ssl-required: external
  #keycloak resource is the client ID
  resource: pmp-client
  use-resource-role-mappings: true
  #The line below will prevent redirect to login page

  bearer-only: true
  credentials:
    secret: Bhw120rFFBSVLciCuictWw5wOuSbJmu2
  public-client: true


#  securityConstraints:
#    - authRoles: [ user, admin ]
#      securityCollections:
#        - name: API Private Data
#          patterns: [ '/todos/search/my-todos/*' ]
#    - authRoles: [ admin ]
#      securityCollections:
#        - name: API
#          patterns: [ '/todos/*' ]

spring:
  application:
    name: spring-security
  datasource:
    password: 1
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    username: pms.waa@gmail.com
    password: pms.waa.password
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable=true
server:
  port: 8081
  netty:
    connection-timeout: 6000